# Change these first
owner: Certegy-Payment-Solutions
repo: cashline.uptime.monitor
sites:
  - name: Cashline Tomcat - PROD
    url: https://certegycashline.com/
  - name: Cashline Java - PROD
    url: https://cashline.certegy.com/health
  - name: Cashline Tomcat - CCE
    url: https://cce.certegycashline.com/
  - name: Cashline Java - CCE
    url: https://cce.cashline.certegy.com/health
  - name: Cashline Tomcat - UAT
    url: https://uat.certegycashline.com/
  - name: Cashline Java - UAT
    url: https://uat.cashline.certegy.com/health
  - name: Cashline Tomcat - QA
    url: https://qa.certegycashline.com/
  - name: Cashline Java - QA
    url: https://qa.cashline.certegy.com/health
  - name: Cashline Tomcat - Dev
    url: https://dev.certegycashline.com/
  - name: Cashline Java - Dev
    url: https://dev.cashline.certegy.com/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /cashline.uptime.monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Cashline Gaming Uptime 
  introTitle: "This page monitors uptime and status of Certegy Gaming Applications."
  introMessage: Please inform AWS Team if you see any outages (awsteam@certegy.com)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
