# Change these first
owner: Certegy-Payment-Solutions
repo: cashline.uptime.tomcat
sites:
  - name: Cashline Tomcat - PROD
    url: https://certegycashline.com/
  - name: Cashline Java - PROD
    url: https://cashline.certegy.com/health
  - name: Cashline Tomcat - CCE
    url: https://cce.certegycashline.com/
  - name: Cashline Java - CCE
    url: https://cce.cashline.certegy.com/health
  - name: Cashline Tomcat - UAT
    url: https://uat.certegycashline.com/
  - name: Cashline Java - UAT
    url: https://uat.cashline.certegy.com/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /cashline.uptime.tomcat
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Cashline Gaming Uptime 
  introTitle: "This app monitors uptime and status page, powered entirely by GitHub."
  introMessage: Alert respective team members if status its red
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
